# Parameters for compiling

ARDUINO_DIR     = /Applications/Development/Arduino1.5.8.app
TARGET          = output
ARDUINO_LIBS    =  


# Avrdude code for programming

BOARD_TAG               = uno 
ARDUINO_PORT            = /dev/ttyACM0
AVRDUDE_ARD_PROGRAMMER  = arduino
AVRDUDE_ARD_BAUDRATE    = 115200


# if you have placed the alternate core in your sketchbook directory, then you can just mention the core name alone. 
#ALTERNATE_CORE = attiny
# If not, you might have to include the full path.
#ALTERNATE_CORE_PATH = /home/sudar/Dropbox/code/arduino-sketches/hardware/attiny/

#BOARD_TAG = trinket5
#ISP_PROG = usbtiny
#MONITOR_PORT = /dev/ttyS0
#ARDUINO_LIBS = TrinketKeyboar

# Arduino makefile

include $(ARDUINO_DIR)/Arduino.mk


